INSERT INTO customers (membership_number, first_name, last_name, address, city, country, zip)
VALUES (10,'Marina', 'Ásgrímsson', 'Klapparstígur 68', 'Reykjavík', 'Iceland', '127'), 
(11,'Bryngeir', 'Óskarsson', 'Thverholt 92', 'Mosfellsbær', 'Iceland', '270'), 
(12,'Smári', 'Baldursson', 'Höfðastígur 76', 'Bolungarvík', 'Iceland', '415'),  
(13,'Úlfar', 'Stefánsson', 'Austvaðsholti 51', 'Hella', 'Iceland', '851'),
(14,'Þórbergur', 'Kristjánsson', 'Akurgerði 9', 'Ísafjörður', 'Iceland', '400'), 
(15,'Arnþrúður', 'Áskelsdóttir', 'Nesvegi 60', 'Hvolsföllur', 'Iceland', '785'), 
(16,'Oddbjörg', 'Eggertsdóttir', 'Fagurhólsmýri 79', 'Fagurhólsmýri', 'Iceland', '785'), 
(17,'Erna', 'Agnarsdóttir', 'Naustavegur 7', 'Vestmannaeyjar', 'Iceland', '900'), 
(18,'Guðmar', 'Tómasson', 'Nesvegur 75', 'Reyðarfjörður', 'Iceland', '730'),
(19,'Esjar', 'Albertsson', 'Fífubarð 48', 'Eyrabakki', 'Iceland', '820'), 
(20,'Sigurgeir', 'Hlöðvarsson', 'Heiðarbraut 6', 'Kópasker', 'Iceland', '671'), 
(21,'Eiður', 'Diðriksson', 'Golfskálinn 53', 'Borgarnes', 'Iceland', '310'),  
(22,'Magnús', 'Þóroddsson', 'Austvaðsholti 52', 'Hella', 'Iceland', '851'),
(23,'Adam', 'Hauksson', 'Solvellir 91', 'Breiðdalsvík', 'Iceland', '760'), 
(24,'Auðunn', 'Arngrímsson', 'Borgarbraut 39', 'Mjóifjörður', 'Iceland', '715'), 
(25,'Snæbjörn', 'Márusson', 'Eyrarlandsvegur 59', 'Tálknafjörður', 'Iceland', '460'), 
(26,'Ásrún', 'Tryggvadóttir', 'Eikarlundur 99', 'Þórshöfn', 'Iceland', '680'), 
(27,'Sigtryggur', 'Sigvaldason', 'Holtagata 52', 'Drangsnes', 'Iceland', '520')